export const workouts = [
  {
    day: 1,
    name: "Legs",
    focus: "Quads, Hamstrings & Glutes",
    exercises: [
      { name: "Barbell squat", sets: 4, reps: 8, type: "compound" },
      { name: "Romanian deadlift", sets: 3, reps: 10, type: "compound" },
      { name: "Leg press", sets: 3, reps: 12, type: "compound" },
      { name: "Walking lunges", sets: 3, reps: 12, type: "compound" },
      { name: "Leg curl", sets: 3, reps: 12, type: "isolation" },
      { name: "Calf raises", sets: 4, reps: 15, type: "isolation" },
    ],
  },
  {
    day: 2,
    name: "Deadlifts & Shoulders",
    focus: "Posterior chain & Delts",
    exercises: [
      { name: "Conventional deadlift", sets: 4, reps: 5, type: "compound" },
      { name: "Overhead press", sets: 4, reps: 8, type: "compound" },
      { name: "Dumbbell lateral raise", sets: 3, reps: 15, type: "isolation" },
      { name: "Face pulls", sets: 3, reps: 15, type: "isolation" },
      { name: "Rear delt fly", sets: 3, reps: 12, type: "isolation" },
    ],
  },
  {
    day: 3,
    name: "Push",
    focus: "Chest & Triceps",
    exercises: [
      { name: "Bench press", sets: 4, reps: 8, type: "compound" },
      { name: "Incline dumbbell press", sets: 3, reps: 10, type: "compound" },
      { name: "Cable chest fly", sets: 3, reps: 12, type: "isolation" },
      { name: "Tricep pushdown", sets: 3, reps: 12, type: "isolation" },
      { name: "Skull crushers", sets: 3, reps: 10, type: "isolation" },
    ],
  },
  {
    day: 4,
    name: "Pull",
    focus: "Back & Biceps",
    exercises: [
      { name: "Pull-ups", sets: 4, reps: 8, type: "compound" },
      { name: "Barbell row", sets: 4, reps: 8, type: "compound" },
      { name: "Seated cable row", sets: 3, reps: 10, type: "compound" },
      { name: "Lat pulldown", sets: 3, reps: 12, type: "compound" },
      { name: "Barbell curl", sets: 3, reps: 10, type: "isolation" },
    ],
  },
  {
    day: 5,
    name: "Isolation",
    focus: "Triceps & Biceps",
    exercises: [
      { name: "Tricep overhead extension", sets: 4, reps: 12, type: "isolation" },
      { name: "Tricep pushdown", sets: 3, reps: 15, type: "isolation" },
      { name: "Hammer curl", sets: 4, reps: 12, type: "isolation" },
      { name: "Concentration curl", sets: 3, reps: 12, type: "isolation" },
      { name: "Cable curl", sets: 3, reps: 15, type: "isolation" },
    ],
  },
  {
    day: 6,
    name: "Core",
    focus: "Abs & Stability",
    exercises: [
      { name: "Plank", sets: 3, reps: "45 sec", type: "isolation" },
      { name: "Hanging leg raises", sets: 3, reps: 12, type: "compound" },
      { name: "Cable crunch", sets: 3, reps: 15, type: "isolation" },
      { name: "Ab wheel rollout", sets: 3, reps: 10, type: "compound" },
      { name: "Side plank", sets: 3, reps: "30 sec", type: "isolation" },
    ],
  },
  {
    day: 7,
    name: "Rest",
    focus: "Recovery",
    exercises: [],
  },
];
